export enum ActionType {
    ASK_AGENT = "ASK_AGENT",
    RESUME = "RESUME",
    CANCEL_TASK = "CANCEL_TASK",
    ASK_USER = "ASK_USER",
    SUSPEND_WORKER = "SUSPEND_WORKER",
    RESUME_WORKER = "RESUME_WORKER",
    EVICT_WORKER = "EVICT_WORKER",
}
